services:
    app.cli.test_command:
        class: App\Cli\TestCommand
        arguments:
            - '@sylius.repository.manufacturer'
            - '@sylius.factory.manufacturer'
            - '@sylius.manager.manufacturer'
        tags:
            - { name: 'console.command' }

    app.cli.import_command:
        class: App\Cli\ImportCommand
        arguments:
            - '@app.importer.taxon'
            - '@app.importer.product_option'
            - '@app.importer.product_attribute'
            - '@app.importer.product'
        tags:
            - { name: 'console.command' }
