services:
    app.form.extension.product_type:
        class: App\Form\Extension\ProductTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductType }
