imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yaml" }

    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusPayPalPlugin/Resources/config/config.yaml" }
    - { resource: "../parameters.yaml" }

parameters:
    sylius_core.public_dir: '%kernel.project_dir%/public'

sylius_api:
    enabled: true

sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_theme:
    sources:
        filesystem:
            scan_depth: 1
            directories:
                - "%kernel.project_dir%/themes"

sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Product\Product

sylius_resource:
    resources:
        sylius.manufacturer:
            driver: doctrine/orm
            classes:
                model: App\Entity\Manufacturer\Manufacturer
